[pytest]

testpaths =
    tests

python_files =
    test_*.py

addopts =
    -v
    --strict-markers

markers =
    api: API tests
    contract: API contract tests that compare implementation with documentation
    ui: UI tests
    smoke: Smoke tests
